name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Deploys to development
  create:
    tags:    # Deploys to production only for tags on main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: self-hosted  # Uses your self-hosted runner

    steps:
      - name: Fix workspace permissions
        run: |
          sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work
          sudo chmod -R 755 /home/ubuntu/actions-runner/_work

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine Deployment Environment
        id: set-env
        run: |
          if [[ $GITHUB_REF_TYPE == "tag" && $GITHUB_BASE_REF == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_ENV
          else
            echo "environment=development" >> $GITHUB_ENV
          fi


      - name: Build and Push Docker Images
        run: |
          docker compose -f docker-compose.${{ env.environment }}.yml build
          docker compose -f docker-compose.${{ env.environment }}.yml push

  deploy_dev:
    name: Deploy to Development
    runs-on: self-hosted
    needs: build-and-push
    if: github.ref == 'refs/heads/main'  # Runs for commits to main

    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.RSA_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into Azure VM and Deploy Development
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} << 'EOF'
            cd /home/ubuntu/actions-runner/_work/Team-76/Team-76

            cp /home/ubuntu/env_files/.env.development .env.development
            cp /home/ubuntu/env_files/.env .env
            echo ".env files copied successfully"

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose.development.yml pull
            docker compose -f docker-compose.development.yml down --remove-orphans
            docker compose -f docker-compose.development.yml up --build -d
            docker system prune -af
          EOF

      - name: Clean Up SSH Key
        run: rm -f private_key.pem

  deploy_prod:
    name: Deploy to Production
    runs-on: self-hosted
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/') && github.base_ref == 'refs/heads/main'  # Only runs for tags on main

    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.RSA_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into Azure VM and Deploy Production
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} << 'EOF'
            cd /home/ubuntu/actions-runner/_work/Team-76/Team-76

            cp /home/ubuntu/env_files/.env.development .env.development
            cp /home/ubuntu/env_files/.env .env
            echo ".env files copied successfully"

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose.production.yml pull
            docker compose -f docker-compose.production.yml down --remove-orphans
            docker compose -f docker-compose.production.yml up --build -d
            docker system prune -af
          EOF

      - name: Clean Up SSH Key
        run: rm -f private_key.pem
